### PR TITLE
Automatic TearDown on Setup errors

### LINKED ISSUE #9: Ensure harness.Setup() errors cleanly
This is to avoid the need to call harness.TearDown() in case setup failed (see for example here: https://github.com/decred/dcrtest/blob/85f922c0880ed7da514ab27df486ce29c4310039/dcrdtest/rpc_harness_test.go#L574-L585).

### PR DESCRIPTION
**Pull request by matheusd**
Fix #9 

This makes failures to run a harness' `SetUp()` function to automatically call `TearDown()` to remove any leaking goroutines. 

Additionally, it fixes a shutdown goroutine leak in the memory wallet and adds a flag to force the harness to keep the node data intact on TearDown.

### CODE REVIEW

File: dcrdtest/rpc_harness_test.go [hunk 1]
```diff
@@ -658,3 +656,135 @@ func TestHarness(t *testing.T) {
...
+	}
+
+	// Perform the teardown.
+	if err := mainHarness.TearDown(); err != nil {
+		t.Fatalf("unable to TearDown test chain: %v", err)
+	}
+
+	// There should be only 2 goroutines live.
+	prof := pprof.Lookup("goroutine")
+	gotCount, wantCount := prof.Count(), 2
```
Comment (davecgh) [inline dcrdtest/rpc_harness_test.go:700]: This is a technique I've not seen before.  I typically do this with channels and/or waitgroups.

I don't have any big objection to it, but this is probably fairly fragile since I suspect it relies on the semantics of the testing framework creating 2 goroutines.

Maybe it should get the count prior to calling `SetUp` and then ensuring it matches that value here so it's robust against framework changes?

File: dcrdtest/rpc_harness.go [hunk 2]
```diff
@@ -214,6 +216,15 @@ func New(t *testing.T, activeNet *chaincfg.Params, handlers *rpcclient.Notificat
 	return h, nil
 }
 
+// ToggleKeepNodeDir flags the Harness on whether to keep or remove its node
+// dir after TearDown is called.
+//
+// This is NOT safe for concurrent access and MUST be called from the same
+// goroutine that calls SetUp and TearDown.
+func (h *Harness) ToggleKeepNodeDir(keep bool) {
```
Comment (davecgh) [inline dcrdtest/rpc_harness.go:224]: Not a big deal, but toggle to me implies it will toggle it, as in flip the current state.  Perhaps just `SetKeepNodeDir(keep bool)`.

File: dcrdtest/rpc_harness_test.go [hunk 3]
```diff
@@ -788,3 +794,37 @@ func TestSetupWithWrongDcrd(t *testing.T) {
 		t.Fatalf("Unexpected error during TearDown: %v", err)
 	}
 }
+
+// TestKeepsNodeDir asserts that when the harness is set to keep the node dir,
+// it is not removed after TearDown().
+func TestKeepsNodeDir(t *testing.T) {
```
Comment (davecgh) [inline dcrdtest/rpc_harness_test.go:800]: `TestKeepNodeDir`?  Either is fine imo, but it's more common to name them `Test<Method>`.

**Review by davecgh — COMMENTED** [review]
Nice updates.  It's more in line with the way I typically prefer to do things where any type of setup is either successful or it fails and cleans everything up itself so nothing is left in a half-initialized state.

File: dcrdtest/rpc_harness_test.go (hunk 1 above)
Comment (matheusd) [reply dcrdtest/rpc_harness_test.go:700]: Point taken. Updating to use before/after count of goroutines. The "2" is indeed due to how the test runtime spawns the individual test functions.

**Comment by matheusd** [comment]
Pushed review fixes: https://github.com/decred/dcrtest/compare/9ac3a9371d76432ac3e3bab47662d7173c45273b..5399d59e8bd7df4b359bf4d5642e0b094f50316a

**Review by davecgh — APPROVED** [review]
